#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Directory structure run file. Run it to see and check your directory structure vs your config."""

# TODOS:
# Clean argparse
# Add main function
# Add rule for unknown directories

import os
import yaml

from structure_printer import print_dir_structure, get_subdirs
from rules import ALL_RULES


def check_rules_equal(dir_structure):
    """Check config rules and implemented rules are the same."""
    config_rules = list(dir_structure['rules'].keys())
    script_rules = list(map(lambda rule: rule.key, ALL_RULES))

    if config_rules != script_rules:
        raise ValueError(
        f"""Config rules and rules implemented are different !
        Config rules: {config_rules}
        Implemented rules: {script_rules}""")


def check_rules(dir_structure):
    """Check user directories follow the rules specified in the config."""
    check_rules_equal(dir_structure)

    def check_directory(directory, prefix_path=''):
        path = prefix_path + directory['path']

        for rule in ALL_RULES:
            rule.check(path)

        for subdir in get_subdirs(directory):
            check_directory(subdir, prefix_path)

    directories = dir_structure['directories']

    for directory in directories:
        check_directory(directory)

    return 0

def main():
    """Main function."""

    # This script's path
    __location__ = os.path.realpath( os.path.join(os.getcwd(), os.path.dirname(__file__)))

    directories_file = os.path.join(__location__, 'directories.yml')

    with open(directories_file, "r", encoding='utf-8') as dir_structure_file:
        try:
            dir_structure = yaml.safe_load(dir_structure_file)

            print_dir_structure(dir_structure)

            check_rules(dir_structure)

        except yaml.YAMLError as exc:
            print("Error when loading yaml:")
            print(exc)


if __name__ == '__main__':
    main()
